sudo: required

matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - sudo bash prepare.sh
        - sh init-sketches.sh
      script:
        - sh build-sketches.sh

    - language: csharp
      before_script:
        - git checkout $TRAVIS_BRANCH
        - sudo bash prepare.sh
        - sh init-tests.sh
      script:
        - sh build-tests.sh
        - sh test-software.sh

