sudo: required

language: python

install:
  - git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
  - git fetch --no-tags
  - git checkout $TRAVIS_BRANCH
  - git pull origin $TRAVIS_BRANCH
  - git submodule update --depth 50
  - sh init-mock-setup.sh
  - sudo bash prepare.sh
  - sh init-all.sh
  - git remote set-url origin https://${GHTOKEN}@github.com/GreenSense/Index.git

script:
  - sh build-all.sh
  - sh test.sh
