sudo: required

language: c#

services:
  - docker

install:
  - git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
  - git fetch --no-tags
  - git checkout $TRAVIS_BRANCH
  - sh prepare.sh
  - sh init.sh
  - git remote set-url origin https://${GHTOKEN}@github.com/GreenSense/Index.git

script:
  - sh build.sh
  - sh test.sh
  - git checkout mobile/linearmqtt/devicecount.txt
  - sh graduate.sh
