sudo: required

language: csharp

mono:
  - latest

services:
  - docker
  - systemd

install:
  - git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
  - git fetch --no-tags
  - git checkout $TRAVIS_BRANCH
  - sh prepare.sh
  - sh init.sh
  - sh set-mqtt-credentials.sh myusername mypassword
  - git remote set-url origin https://${GHTOKEN}@github.com/GreenSense/Index.git

script:
  - sh update-submodules.sh
  - sh build.sh
  - sh test.sh
  - sh clean.sh
  - sh graduate.sh
